In [1]:
liberies : they are collection of modules and fumction to perform specific tasks.

data anaylsis
*panda :data menuplation 
*num py(numerical python): multi-dimentional arrays and mathematical operations 

*matplotlib,seaborn,plotly:data visulazition
*satatistic:

machine learning
*sklearn (scikit learn) : machine learning 

deep learning
*keras : deep learning 
tensorflow :google
pytorch : facebook

SyntaxError: invalid syntax (2193370137.py, line 1)

In [1]:
import pandas as pd

serise data : containe pnly one column data
data frame : 2D data in tabular format

In [2]:
s1 = pd.Series([2,5,7,8,2,9,10])
s1

0     2
1     5
2     7
3     8
4     2
5     9
6    10
dtype: int64

create sict for 2 stu details
sid , snnME .PHNO

In [3]:
DICT1 = {'SID':[123,124,125,126],'SNAME':['A','B','C','D'],'PHNO':[124567890,9874561,4712582,258963147]}
DICT1

{'SID': [123, 124, 125, 126],
 'SNAME': ['A', 'B', 'C', 'D'],
 'PHNO': [124567890, 9874561, 4712582, 258963147]}

In [7]:
d1=pd.DataFrame(DICT1)
d1

   SID SNAME       PHNO
0  123     A  124567890
1  124     B    9874561
2  125     C    4712582
3  126     D  258963147

In [4]:
emp=pd.read_excel(r"C:\Users\DELL\OneDrive\Desktop\MLP 3pm\python data\emp_data.xlsx")
emp

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [5]:
stu=pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\MLP 3pm\python data\studata.txt")
stu

   sid    sname            emialid address  phoneno
0    1    priya    priya@gmail.com     dvg     9876
1    2  karthik  karthik@gmail.com     blr    12345
2    3    karan                NaN     msr    34567

In [6]:
cpt1 = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\chipotle.tsv",sep="\t")
cpt1

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [28]:
cars=pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\mtcars.csv")

In [9]:
cars.shape

(32, 12)

In [10]:
cars.shape[0]

32

In [11]:
cars.shape[1]

12

In [12]:
cars.head(10)

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

In [13]:
cars.tail()

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [14]:
temp = cars.sample(15,random_state=24)
temp

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

In [15]:
cars.dtypes

manufacturer     object
mpg             float64
cyl               int64
disp            float64
hp                int64
drat            float64
wt              float64
qsec            float64
vs                int64
am                int64
gear              int64
carb              int64
dtype: object

In [19]:
cars.columns

Index(['manufacturer', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [16]:
cars.isna().sum()

manufacturer    0
mpg             0
cyl             0
disp            0
hp              0
drat            0
wt              0
qsec            0
vs              0
am              0
gear            0
carb            0
dtype: int64

In [18]:
cars.duplicated().sum()

np.int64(0)

In [17]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  32 non-null     object
 1   mpg           32 non-null     float64
 2   cyl           32 non-null     int64
 3   disp          32 non-null     float64
 4   hp            32 non-null     int64
 5   drat          32 non-null     float64
 6   wt            32 non-null     float64
 7   qsec          32 non-null     float64
 8   vs            32 non-null     int64
 9   am            32 non-null     int64
 10  gear          32 non-null     int64
 11  carb          32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [23]:
cars.mpg

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [ ]:
cars['mpg']

In [30]:
cars[['mpg','hp']]

     mpg   hp
0   21.0  110
1   21.0  110
2   22.8   93
3   21.4  110
4   18.7  175
5   18.1  105
6   14.3  245
7   24.4   62
8   22.8   95
9   19.2  123
10  17.8  123
11  16.4  180
12  17.3  180
13  15.2  180
14  10.4  205
15  10.4  215
16  14.7  230
17  32.4   66
18  30.4   52
19  33.9   65
20  21.5   97
21  15.5  150
22  15.2  150
23  13.3  245
24  19.2  175
25  27.3   66
26  26.0   91
27  30.4  113
28  15.8  264
29  19.7  175
30  15.0  335
31  21.4  109

In [31]:
cars['half_mpg']=cars['mpg']/2
cars

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,half_mpg
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,10.50
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,10.50
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,11.40
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,10.70
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,9.35
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,9.05
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.15
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,12.20
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.40
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.60
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,8.90
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.20
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.65
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,7.60
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,5.20
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,5.20
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,7.35
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,16.20
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,15.20
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,16.95
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.75
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,7.75
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,7.60
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,6.65
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,9.60
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,13.65
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,13.00
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,15.20
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.90
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,9.85
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.50
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,10.70

In [ ]:
cars['drat']=cars['drat']+10
cars

In [ ]:
del cars['half_mpg']
cars

In [ ]:
cars.drop(['am','gear','carb'],axis=1)

In [ ]:
cars.drop(['am','gear','carb'],axis=1, inplace=True)

In [ ]:
cars

In [2]:
import pandas as pd

In [19]:
cars = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\mtcars.csv")
cars

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
# extract only float value
cars.select_dtypes(include=float)

In [ ]:
# extract numerical value
cars.select_dtypes(exclude=float)

In [ ]:
# extract text only
cars.select_dtypes(include=object)

In [ ]:
# extract unique value from cyl column
cars['cyl'].unique()

In [ ]:
# extract column which are having < 10 unique values
cars['cyl'].nunique()

In [ ]:
cols = []
for i in cars.column:
    if (cars [i].nunique()<10):
        cols.append(i)
cars[cols]
Print(cols)
for i in cols

In [ ]:
cars['cyl'].value_count()

In [29]:
cars=[]
for i in cars['cyl'].unique();
print("cyl",i)
print("num of recors=",cars[car['cyl']==i]/shape([0])

SyntaxError: invalid syntax (4239746725.py, line 2)

In [25]:
cars[cars['cyl']==6].shape[0]

7

In [24]:
# from cars data extract the records who hp is less then 100
cars[cars['hp']<100]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2

In [34]:
# from cars data extract the records who hp between 100 to 200
cars[(cars['hp']>=100) & (cars['hp']<200)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [39]:
# from cars data extract the records who hp between <100 to >200
cars[(cars['hp']<100) | (cars['hp']>200)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [44]:
# extract the records either gear 4 or carb 1
cars[(cars['gear']==4) & (cars['carb']==1)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1

In [4]:
# extract the records of 4 cyl cars with 4 gears
cars[(cars['cyl']==4) & (cars['gear']==4)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [5]:
# calculate max,min,avg of mpg
cars['mpg'].max()

33.9

In [6]:
# min
cars['mpg'].min()

10.4

In [7]:
# avg
cars['mpg'].mean().round(2)

np.float64(20.09)

In [15]:
# count of automatic cars
len(cars[cars['am']==1])

13

In [18]:
(cars['gear']==4)

0      True
1      True
2      True
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18     True
19     True
20    False
21    False
22    False
23    False
24    False
25     True
26    False
27    False
28    False
29    False
30    False
31     True
Name: gear, dtype: bool

In [24]:
# count of automatic num of 1
cars['am'].tolist().count(1)

13

In [25]:
cars['mpg'].std()

6.026948052089105

In [26]:
cars['mpg'].var()

36.32410282258065

In [27]:
cars['mpg'].median()

19.2

In [ ]:
extracting particular rows and column using iloc (index based)and loc(name based)

syntex of iloc
var.iloc[row slicing.col slicing]
var.[step row:spp row:ss row, stop col:spp col:ss col]
deaul start position is 0
dtop positionis upto end step size is 1

In [32]:
# extraxt 
cars.iloc[0:5:1]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [38]:

cars.iloc[0:,-5:]

     qsec  vs  am  gear  carb
0   16.46   0   1     4     4
1   17.02   0   1     4     4
2   18.61   1   1     4     1
3   19.44   1   0     3     1
4   17.02   0   0     3     2
5   20.22   1   0     3     1
6   15.84   0   0     3     4
7   20.00   1   0     4     2
8   22.90   1   0     4     2
9   18.30   1   0     4     4
10  18.90   1   0     4     4
11  17.40   0   0     3     3
12  17.60   0   0     3     3
13  18.00   0   0     3     3
14  17.98   0   0     3     4
15  17.82   0   0     3     4
16  17.42   0   0     3     4
17  19.47   1   1     4     1
18  18.52   1   1     4     2
19  19.90   1   1     4     1
20  20.01   1   0     3     1
21  16.87   0   0     3     2
22  17.30   0   0     3     2
23  15.41   0   0     3     4
24  17.05   0   0     3     2
25  18.90   1   1     4     1
26  16.70   0   1     5     2
27  16.90   1   1     5     2
28  14.50   0   1     5     4
29  15.50   0   1     5     6
30  14.60   0   1     5     8
31  18.60   1   1     4     2

In [40]:
# extract even indexed rows amd odd indexed column
cars.iloc[0::2,1::2]

     mpg   disp  drat   qsec  am  carb
0   21.0  160.0  3.90  16.46   1     4
2   22.8  108.0  3.85  18.61   1     1
4   18.7  360.0  3.15  17.02   0     2
6   14.3  360.0  3.21  15.84   0     4
8   22.8  140.8  3.92  22.90   0     2
10  17.8  167.6  3.92  18.90   0     4
12  17.3  275.8  3.07  17.60   0     3
14  10.4  472.0  2.93  17.98   0     4
16  14.7  440.0  3.23  17.42   0     4
18  30.4   75.7  4.93  18.52   1     2
20  21.5  120.1  3.70  20.01   0     1
22  15.2  304.0  3.15  17.30   0     2
24  19.2  400.0  3.08  17.05   0     2
26  26.0  120.3  4.43  16.70   1     2
28  15.8  351.0  4.22  14.50   1     4
30  15.0  301.0  3.54  14.60   1     8

In [48]:
cars[::1]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [47]:
# revers the column name
cars.iloc[::-1,::-1]

,carb,gear,am,vs,qsec,wt,drat,hp,disp,cyl,mpg,manufacturer
31,2,4,1,1,18.60,2.780,4.11,109,121.0,4,21.4,Volvo 142E
30,8,5,1,0,14.60,3.570,3.54,335,301.0,8,15.0,Maserati Bora
29,6,5,1,0,15.50,2.770,3.62,175,145.0,6,19.7,Ferrari Dino
28,4,5,1,0,14.50,3.170,4.22,264,351.0,8,15.8,Ford Pantera L
27,2,5,1,1,16.90,1.513,3.77,113,95.1,4,30.4,Lotus Europa
26,2,5,1,0,16.70,2.140,4.43,91,120.3,4,26.0,Porsche 914-2
25,1,4,1,1,18.90,1.935,4.08,66,79.0,4,27.3,Fiat X1-9
24,2,3,0,0,17.05,3.845,3.08,175,400.0,8,19.2,Pontiac Firebird
23,4,3,0,0,15.41,3.840,3.73,245,350.0,8,13.3,Camaro Z28
22,2,3,0,0,17.30,3.435,3.15,150,304.0,8,15.2,AMC Javelin
21,2,3,0,0,16.87,3.520,2.76,150,318.0,8,15.5,Dodge Challenger
20,1,3,0,1,20.01,2.465,3.70,97,120.1,4,21.5,Toyota Corona
19,1,4,1,1,19.90,1.835,4.22,65,71.1,4,33.9,Toyota Corolla
18,2,4,1,1,18.52,1.615,4.93,52,75.7,4,30.4,Honda Civic
17,1,4,1,1,19.47,2.200,4.08,66,78.7,4,32.4,Fiat 128
16,4,3,0,0,17.42,5.345,3.23,230,440.0,8,14.7,Chrysler Imperial
15,4,3,0,0,17.82,5.424,3.00,215,460.0,8,10.4,Lincoln Continental
14,4,3,0,0,17.98,5.250,2.93,205,472.0,8,10.4,Cadillac Fleetwood
13,3,3,0,0,18.00,3.780,3.07,180,275.8,8,15.2,Merc 450SLC
12,3,3,0,0,17.60,3.730,3.07,180,275.8,8,17.3,Merc 450SL
11,3,3,0,0,17.40,4.070,3.07,180,275.8,8,16.4,Merc 450SE
10,4,4,0,1,18.90,3.440,3.92,123,167.6,6,17.8,Merc 280C
9,4,4,0,1,18.30,3.440,3.92,123,167.6,6,19.2,Merc 280
8,2,4,0,1,22.90,3.150,3.92,95,140.8,4,22.8,Merc 230
7,2,4,0,1,20.00,3.190,3.69,62,146.7,4,24.4,Merc 240D
6,4,3,0,0,15.84,3.570,3.21,245,360.0,8,14.3,Duster 360
5,1,3,0,1,20.22,3.460,2.76,105,225.0,6,18.1,Valiant
4,2,3,0,0,17.02,3.440,3.15,175,360.0,8,18.7,Hornet Sportabout
3,1,3,0,1,19.44,3.215,3.08,110,258.0,6,21.4,Hornet 4 Drive
2,1,4,1,1,18.61,2.320,3.85,93,108.0,4,22.8,Datsun 710
1,4,4,1,0,17.02,2.875,3.90,110,160.0,6,21.0,Mazda RX4 Wag
0,4,4,1,0,16.46,2.620,3.90,110,160.0,6,21.0,Mazda RX4

In [56]:
# loc extract 1st five row with 1st five column
cars.loc[0:4,'manufacturer':'hp']

        manufacturer   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  160.0  110
1      Mazda RX4 Wag  21.0    6  160.0  110
2         Datsun 710  22.8    4  108.0   93
3     Hornet 4 Drive  21.4    6  258.0  110
4  Hornet Sportabout  18.7    8  360.0  175

In [20]:
# rows values
#rows= 1,5,13,17,22,19
# col =hp,wt,vs,gear

cars.loc[[1,5,13,17,22,19],['hp','wt','vs','gear']]

     hp     wt  vs  gear
1   110  2.875   0     4
5   105  3.460   1     3
13  180  3.780   0     3
17   66  2.200   1     4
22  150  3.435   0     3
19   65  1.835   1     4

In [3]:
import pandas as pd

In [3]:
sale1=pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\Sales Transactions-2017.csv")
sale1

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [4]:
sale2=pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\Sales Transactions-2018.csv")
sale2

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [5]:
sale3=pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\Sales Transactions-2019.csv")
sale3

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [6]:
sales = pd.concat([sale1,sale2,sale3],ignore_index=True)
sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [7]:
sales.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [8]:
sales.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [9]:
sales.dropna(inplace=True,ignore_index=True)
sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:898,Lock,Vishnu 250ml,100,30,"3,000.00",100,"5,400.00"
1,,,khader vali late en,,,,,,
2,,,try,,,,,,
3,,,DUMMY ENTRY,,,,,,
4,,,dummy entry,,,,,,
...,...,...,...,...,...,...,...,...,...
3289,,,8/10 late entry,,,,,,
3290,,,10-Jul,,,,,,
3291,10/10/2019,Sal:4925,SLST-GDR,500ML PLASTIC BOULS,"1,000.00",3.55,"3,550.00","3,550.00","4,090.00"
3292,,,vinayaka sweets-kot,,,,,,
3293,,,hagunta,,,,,,

In [10]:
sales.isna().sum()

Date              0
Voucher           0
Party             0
Product           0
Qty               0
Rate              0
Gross             0
Disc              0
Voucher Amount    0
dtype: int64

In [11]:
sales.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [12]:
sales['Date'].replace(' ',0,inplace=True)
sales

C:\Users\DELL\AppData\Local\Temp\ipykernel_9344\2417437423.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales['Date'].replace(' ',0,inplace=True)

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:898,Lock,Vishnu 250ml,100,30,"3,000.00",100,"5,400.00"
1,0,,khader vali late en,,,,,,
2,0,,try,,,,,,
3,0,,DUMMY ENTRY,,,,,,
4,0,,dummy entry,,,,,,
...,...,...,...,...,...,...,...,...,...
3289,0,,8/10 late entry,,,,,,
3290,0,,10-Jul,,,,,,
3291,10/10/2019,Sal:4925,SLST-GDR,500ML PLASTIC BOULS,"1,000.00",3.55,"3,550.00","3,550.00","4,090.00"
3292,0,,vinayaka sweets-kot,,,,,,
3293,0,,hagunta,,,,,,

In [43]:
sales = pd.concat([sale, sale1, sale2], axis=0, ignore_index=True)
sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [44]:
for i in sales.columns:
    sales[i].replace(' ',0,inplace=True)
sales

C:\Users\DELL\AppData\Local\Temp\ipykernel_14652\1155700649.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales[i].replace(' ',0,inplace=True)

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [14]:
sales['Qty'] = sales['Qty'].str.replace(",","")
sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:898,Lock,Vishnu 250ml,100,30,"3,000.00",100,"5,400.00"
1,0,,khader vali late en,,,,,,
2,0,,try,,,,,,
3,0,,DUMMY ENTRY,,,,,,
4,0,,dummy entry,,,,,,
...,...,...,...,...,...,...,...,...,...
3289,0,,8/10 late entry,,,,,,
3290,0,,10-Jul,,,,,,
3291,10/10/2019,Sal:4925,SLST-GDR,500ML PLASTIC BOULS,1000.00,3.55,"3,550.00","3,550.00","4,090.00"
3292,0,,vinayaka sweets-kot,,,,,,
3293,0,,hagunta,,,,,,

In [39]:
sales['Gross'] = sales['Gross'].str.replace(",","")
sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:898,Lock,Vishnu 250ml,100,30,3000.00,100,"5,400.00"
1,0,,khader vali late en,,,,,,
2,0,,try,,,,,,
3,0,,DUMMY ENTRY,,,,,,
4,0,,dummy entry,,,,,,
...,...,...,...,...,...,...,...,...,...
3289,0,,8/10 late entry,,,,,,
3290,0,,10-Jul,,,,,,
3291,10/10/2019,Sal:4925,SLST-GDR,500ML PLASTIC BOULS,1000.00,3.55,3550.00,"3,550.00","4,090.00"
3292,0,,vinayaka sweets-kot,,,,,,
3293,0,,hagunta,,,,,,

In [40]:
sales['Disc'] = sales['Disc'].str.replace(",","")
sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:898,Lock,Vishnu 250ml,100,30,3000.00,100,"5,400.00"
1,0,,khader vali late en,,,,,,
2,0,,try,,,,,,
3,0,,DUMMY ENTRY,,,,,,
4,0,,dummy entry,,,,,,
...,...,...,...,...,...,...,...,...,...
3289,0,,8/10 late entry,,,,,,
3290,0,,10-Jul,,,,,,
3291,10/10/2019,Sal:4925,SLST-GDR,500ML PLASTIC BOULS,1000.00,3.55,3550.00,3550.00,"4,090.00"
3292,0,,vinayaka sweets-kot,,,,,,
3293,0,,hagunta,,,,,,

In [46]:
sales['Amount'] = sales['Amount'].str.replace(",","")
sales

KeyError: 'Amount'

In [21]:
sales['Qty'] = sales['Qty'].astype(float)
sales.dtypes

ValueError: could not convert string to float: ' '

on insurance data
1) each region wise total expenses
2) gender wise avg bmi and expenses
3) each region,each children and 
somker class wise total expenses

    use: group by and pivot table

In [4]:
ins = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\insurance.csv")
ins

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [5]:
# Group by region and sum the charges 
ins.groupby('region')['expenses'].sum()

region
northeast    4343668.64
northwest    4035711.93
southeast    5363689.80
southwest    4012754.82
Name: expenses, dtype: float64

In [9]:
# region and sum the charges  by pivot
pd.pivot_table(data=ins,values='expenses',index='region', aggfunc='sum')

             expenses
region
northeast  4343668.64
northwest  4035711.93
southeast  5363689.80
southwest  4012754.82

In [16]:
# Group by region and sum the charges  in ascending order
ins.groupby('region')['expenses'].sum().sort_values()

region
southwest    4012754.82
northwest    4035711.93
northeast    4343668.64
southeast    5363689.80
Name: expenses, dtype: float64

In [17]:
# Group by region and sum the charges  in decending order
ins.groupby('region')['expenses'].sum().sort_values(ascending=False)

region
southeast    5363689.80
northeast    4343668.64
northwest    4035711.93
southwest    4012754.82
Name: expenses, dtype: float64

In [18]:
# gender wise avg bmi and expenses by group by
ins.groupby('sex')[['bmi', 'expenses']].mean().round()

         bmi  expenses
sex
female  30.0   12570.0
male    31.0   13957.0

In [ ]:
# gender wise avg bmi and expenses by pivot 
pd.pivot_table(data=ins,values=['bmi','expensen'],index

In [25]:
#  each region,each children and 
# somker class wise total expenses

pd.pivot_table (data=ins,values='expenses',index='region',columns=['smoker','children'],aggfunc='mean')

smoker              no                                                         \
children             0            1             2             3             4
region
northeast  8072.292479  9898.238182  11669.296190   7653.362069  14485.194286
northwest  7544.599630  7981.625846   9950.850182  10547.913333   9321.926000
southeast  7060.081624  8016.476164   7519.505833  11986.612083  14451.024000
southwest  7754.155044  7647.231857   8946.972250   8650.186875   9281.694000

smoker                            yes                              \
children              5             0             1             2
region
northeast   6978.973333  28167.025385  32340.127273  22695.814444
northwest   8965.800000  28333.342083  26470.358889  31031.635455
southeast  10115.441667  35515.494500  32503.010455  37619.046667
southwest   6932.858571  30851.768800  34549.955000  37569.401765

smoker
children              3         4         5
region
northeast  34003.914000       NaN       NaN
northwest  36160.173077  21472.48       NaN
southeast  32551.445455       NaN       NaN
southwest  21616.882000  29062.18  19023.26

In [20]:
#  each region,each children and 
# somker class wise total expenses by groupby
ins.groupby(by=['region','children','smoker'])['expenses'].mean().round()

region     children  smoker
northeast  0         no         8072.0
                     yes       28167.0
           1         no         9898.0
                     yes       32340.0
           2         no        11669.0
                     yes       22696.0
           3         no         7653.0
                     yes       34004.0
           4         no        14485.0
           5         no         6979.0
northwest  0         no         7545.0
                     yes       28333.0
           1         no         7982.0
                     yes       26470.0
           2         no         9951.0
                     yes       31032.0
           3         no        10548.0
                     yes       36160.0
           4         no         9322.0
                     yes       21472.0
           5         no         8966.0
southeast  0         no         7060.0
                     yes       35515.0
           1         no         8016.0
                     yes       32503.0
           2         no         7520.0
                     yes       37619.0
           3         no        11987.0
                     yes       32551.0
           4         no        14451.0
           5         no        10115.0
southwest  0         no         7754.0
                     yes       30852.0
           1         no         7647.0
                     yes       34550.0
           2         no         8947.0
                     yes       37569.0
           3         no         8650.0
                     yes       21617.0
           4         no         9282.0
                     yes       29062.0
           5         no         6933.0
                     yes       19023.0
Name: expenses, dtype: float64

In [26]:
sales = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\MLP 3pm\python data\sales_data_sample.csv")
sales

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New

In [37]:
sales['total_sales']=sales['UnitPrice'].sum()
sales

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,total_sales
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,504250
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New,504250
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,504250
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,504250
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,504250
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular,504250
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New,504250
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,504250
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,504250
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New,504250
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,504250
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New,504250
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,504250
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,504250
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular,504250
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New,504250
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,504250
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,504250
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,504250
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New,504250

In [38]:
sales.groupby('region')[''].sum()

KeyError: 'region'